name: blocktools_hub
description: A lightweight Minecraft Utility App for Android and Web.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  http: ^1.1.0 # API calls ke liye add kiya gaya hai
  shared_preferences: ^2.2.2 # Local data storage ke liye add kiya gaya hai



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # HTML renderer explicitly mention karne ke liye web build command use karenge
